### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [strigo/pystrigo#6]
I would like to use your api client. It is installed and setup as described in the readme and throws an error at line 1:    

```
from strigo import Strigo
```

The exception is:
```
$ImportError: cannot import name 'endpoints' from partially initialized module 'strigo' (most likely due to a circular import) (/Users/flb/.pyenv/versions/3.9.5/lib/python3.9/site-packages/strigo/__init__.py)
```

If I run a test script directly in the pystrigo directory it works. Can you give me a hint what may be the problem?
Thanks

**Comment by nir0s** [comment]
Seems like this is a regression in cpython's upstream.

https://github.com/dask/distributed/issues/4168

Can you try and use Python 3.7/8?

**Comment by Bernhard-Fluehmann** [comment]
Hi @nir0s Thank you for your fast reply.

Same problem with python 3.8.1    
````
➜  strigo-dynamic-inventory git:(master) ✗ python strigo_test.py
Traceback (most recent call last):
  File "strigo_test.py", line 1, in <module>
    from strigo import Strigo
  File "/Users/flb/.pyenv/versions/3.8.1/lib/python3.8/site-packages/strigo/__init__.py", line 1, in <module>
    from .client import Strigo  # pylint-disable
  File "/Users/flb/.pyenv/versions/3.8.1/lib/python3.8/site-packages/strigo/client.py", line 10, in <module>
    from . import endpoints
ImportError: cannot import name 'endpoints' from partially initialized module 'strigo' (most likely due to a circular import) (/Users/flb/.pyenv/versions/3.8.1/lib/python3.8/site-packages/strigo/__init__.py)
````

and python 3.7.2    
````
➜  strigo-dynamic-inventory git:(master) ✗ python strigo_test.py                                                                      
Traceback (most recent call last):
  File "strigo_test.py", line 1, in <module>
    from strigo import Strigo
  File "/Users/flb/.pyenv/versions/3.7.2/lib/python3.7/site-packages/strigo/__init__.py", line 1, in <module>
    from .client import Strigo  # pylint-disable
  File "/Users/flb/.pyenv/versions/3.7.2/lib/python3.7/site-packages/strigo/client.py", line 10, in <module>
    from . import endpoints
ImportError: cannot import name 'endpoints' from 'strigo' (/Users/flb/.pyenv/versions/3.7.2/lib/python3.7/site-packages/strigo/__init__.py)
````


Any other ideas?

**Comment by nir0s** [comment]
Yeah... that's absolutely my bad here.

Fixed here https://github.com/strigo/pystrigo/commit/2814a74548664f07fdb039ff54a4024ba8cbcd0b.

Please try now.
